CREATE DATABASE NETFLIX_DB;

USE NETFLIX_DB;

SHOW TABLES;

-- CREATING THE TABLE STRUCTURE BASED ON DATASET 
CREATE TABLE IF NOT EXISTS NETFLIX_DATASET
(
SHOW_ID INT,
TITLE VARCHAR(150),
DIRECTOR VARCHAR(200),
CAST TEXT,
COUNTRY VARCHAR(150),
DATA_ADDED VARCHAR(30),
RELEASED_YEAR VARCHAR(10),
RATING VARCHAR(10),
DURATION VARCHAR(20),
CATEGORY_OF_MOVIE TEXT,
DESCRIPTION_OF_MOVIE TEXT,
TYPE_OF_SHOW VARCHAR(100)
);

SHOW TABLES;
DESC NETFLIX_DATASET;

SELECT * FROM NETFLIX_DATASET;
-- METHOD 1 TO LOAD DATA IN TABLE FROM FILE IS TO DO BY CLICKING ON 'netflix_db' THEN SELECT 'table data import wizard' then follow instruction in video
-- method 1 not for company level implimentation use METHOD 2 INSTEAD called " 'LOAD DATA INFILE' COMMAND"
TRUNCATE TABLE NETFLIX_DATASET;